### ISSUE TITLE
Improve Center Of Gravity Computation.

### ISSUE THREAD

**Issue by william-swy** [Ivan-Bao/WB-Dynamics#13]
Currently the center of gravity computation is a bit messy and perhaps a bit hard coded.

Improve center of gravity computation that factors in mass distribution from burnt fuel and overall rocket length and diameter.

**Comment by zamenshi** [comment]
by "improve centre of gravity computation" we actually mean build a new one; the way that centre of gravity is calculated right now is 23 lines of incomprehensibility

**Comment by william-swy** [comment]
Updated implementation can be found [here](https://github.com/Ivan-Bao/WB-Dynamics/blob/trajectory-distribution/src/quaternion/ComputeCGRelBase.m)
